- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/SwingList.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/GuideView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListCellView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
🌱 작업한 브랜치
- feature/#8
- Resolved: #8
> [Feat]Tering#8-가이드, 개수 뷰 네비게이션 완료

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
🌱 작업한 브랜치
- feature/#10
- 스윙 개수뷰 레이아웃 작성
- 맨 위 글씨가 뭔가 작은데, 글씨 크기 확인 필요
- Resolved: #10
> [Design]Tering#10-스윙 개수뷰 레이아웃 작성

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
🌱 작업한 브랜치
- feature/#14
- 3, 2, 1, 시작! + circle progress bar
- 시작! 후 화면 넘어가기
- 저한테 찾아오면 보여드림 ㅋㅋ
- Resolved: #14
> Feature/#14WatchOS-준비 뷰 구현

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
🌱 작업한 브랜치
- feature/#17
- 측정 뷰 레이아웃 만들기
- 몇 초 뒤 다시 화면 뒤로 가기까지 완료 
- PERFECT, BAD 등은 데이터 모델 생성하고 만들어야 할 듯요
- Resolved: #17
> Feature/#17: WatchOS- 측정 뷰 레이아웃

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
🌱 작업한 브랜치
- feature/#18
- 스윙이 완료되었을 때 스윙완료!가 뜨면서 다음 화면으로 넘어가는 것 완료
- Resolved: #18
> Feature/#18: WatchOS-스윙 완료 뷰 완성

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
🌱 작업한 브랜치
- feature/#31
- 네비게이션 백버튼 전면 수정
- NavigatioinStack을 사용하하고 백버튼 히든해도 그 다음것의 흐름이 끊기지 않네요
- Resolved: #31
> Feature/#31 [Feat]WatchOS-네비게이션 수정

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
🌱 작업한 브랜치
- feature/#36
- 요약뷰 레이아웃 
- Resolved: #36
> [Feat]#36-요약뷰2번 레이아웃 완료

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
🌱 작업한 브랜치
- feature/#38
- 요약뷰 3번째 레이아웃
- 정지 버튼 클릭 시 바로 요약뷰로 넘기기
- Resolved: #38
> Feature/#38:WatchOS-요약뷰 3번째 레이아웃

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Extension/CircleProgressBar.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CompleteView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ReadyView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingResultView.swift
🌱 작업한 브랜치
- feature/#46
- 디자이너가 원하시는 패딩을 위하여 
- Resolved: #46
> [Design]#46-디자인 레이아웃 지정

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/SwingList.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/CountingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/ResultView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingCountView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
🌱 작업한 브랜치
- feature/#41
- 한 사이클 돌 수 있도록 만듦
- 근데 NavigationStack은 목록 같은 것을 타고타고 들어갈 때 사용하는 것 같음,,,
- NavigationStack은 View기반이 아니라 Data 기반이기 때문에, Data를 먼저 설정한 다음 Data를 기반으로 path를 옮기는 것인데, 
지금 이미 처음 구조를 짤 때 그렇게 짜지 않았어서 그렇게 바꾸려면 매우 큰 공사가 필요함,,,
- 따라서 이건 나중에 리팩토링할 때 정도에 바꾸는 것으로 하기~
- 지금은 그냥 마지막 화면에서도 계속 NavigationLink로 첫 번째 화면까지 가도록 만들었음 ㅋㅋ
- Resolved: #41
> Feature/#41 NavigationStack 관련

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/MC3_F4_DoWonGyoRiApp.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Model/DataModel.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Model/EmitterManager.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Model/HapticManager.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/CongreteModalView/CongreteModalView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/CongreteModalView/EmitterView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/ContentView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/MainView/MainView.swift
🌱 작업한 브랜치
- feature/#57
CongreteModal을 완성했습니다.
싱글톤 패턴을 활용하여 애니메이션을 켜고 끄는 변수를 제어합니다.
추가로 팝업 되기 전에 햅틱도 넣었습니다.
- Resolved: #57
> Feature/#57 CongreteModal 완성

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Resource/CustomBackButton.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Resource/Resource.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/GuideView/GuideView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/SettingView/SettingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/SettingView/UserInfoSettingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/SettingView/UserProfileSettingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/SettingView/UserStrokeSettingView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/TodayDetailView/TodayDetailView.swift
🌱 작업한 브랜치
- feature/#59
디자인 오류 사항을 수정했습니다.
- Resolved: #59
> Feature/#59 디자인 수정

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/SettingView/UserProfileSettingView.swift
🌱 작업한 브랜치
- feature/#61
- 
UserProfileSettingView 칭호 피커 디자인 수정 완료
- Resolved: #61
> [Feat] #61 - UserProfileSettingView 칭호 피커 디자인 수정 완료

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/MeasuringView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/SwingListView.swift
🌱 작업한 브랜치
- feature/#16
- 측정 중 뷰 완성 및 List Carousel 적용시킴
- Resolved: #16
> [Feat]#16-측정 중 뷰 완성 및 List CarouselListStyle 적용

- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/MC3_F4_DoWonGyoRiApp.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/Model/WatchViewModel.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi Watch App/View/WatchTestView.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi.xcodeproj/project.pbxproj
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/MC3_F4_DoWonGyoRiApp.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/Model/PhoneViewModel.swift
- MC3-F4-DoWonGyoRi/MC3-F4-DoWonGyoRi/View/PhoneTestView.swift
🌱 작업한 브랜치
- test/REi
- Watch Connectivity 테스트용 코드 추가
- Resolved: #
> [Add] Watch Connectivity 테스트용 코드 추가

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering/MC3_TeringApp.swift
- MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
- MC3_Tering/MC3_Tering/View/TestPhoneView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
- MC3_Tering/MC3_Tering_Watch Watch App/Model/HealthResultInfo.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
🌱 작업한 브랜치
- feature/#73
- WatchConnectivity 연동 완료
- iOS 기준 PhoneTestView()를 통해 확인할 수 있습니다.
- Resolved: #73
> Feature/#73 WatchConnectivity 연동

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
🌱 작업한 브랜치
- feature/#90
- 디지털 크라운 완성
- 버튼 색상 다시 조정하기
- Resolved: #90
> [Feat]#90-디지털 크라운 완성

- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
🌱 작업한 브랜치
- feature/#93
- 디지털 크라운 버튼 완료
- Resolved: #93
> Feature/#93 WatchOS-디지털 크라운 버튼 제작 완료

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingResultView.swift
🌱 작업한 브랜치
- feature/#97
- 운동 시작 버튼 누른 이후 ML 모델 관련 동작 처리
- 시작 버튼 누르고 CountingView 나타나면 모델 불러오고 모션 추적 시작
- 스윙 감지 시 MeasuringView로 넘어가도록 화면 처리
- SwingResultView에 스윙 감지 결과 반영
- 운동 종료 버튼 누르면 모션 추적 종료
- Resolved: #
> Feature/#97 - 운동 시작 이후 Activity Classifier 모델 동작 처리

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering_Watch Watch App/Extension/CircleProgressBar.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCompleteView.swift
🌱 작업한 브랜치
- feature/#105
- 달성완료 프로그레스바 크기 조정
- 측정 중 높이 조정
- Resolved: #105
> Design/#105 WatchOS- 자잘한 수정

- MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/MeasuringView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingCountView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingListView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/SwingResultView.swift
🌱 작업한 브랜치
- feature/#106
- 햅틱 넣기
- 첫 번째 화면 변경
- Resolved: #106
> Feature/#106 WatchOS- 햅틱 넣기

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
- MC3_Tering/MC3_Tering_Watch Watch App/Model/HealthKitManager.swift
- MC3_Tering/MC3_Tering_Watch Watch App/Model/WorkoutManager.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
🌱 작업한 브랜치
- feature/#114
- 스윙 감지가 백그라운드에서도 이루어지도록 하기 위한 기본 세팅
- Background Modes Capability 추가
- WorkoutManager.swift 파일 추가
- HealthKit의 HKWorkoutSession으로 운동 세션을 열어주면 앱이 백그라운드에서도 동작함
- WorkoutManager.swift 파일이 이후 HealthKitManager.swift 파일 대체
- Resolved: #
> Feature/#114 - watchOS 백그라운드 모드 관련 세팅

- MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/CountingView.swift
- WorkoutManager() 객체 활용 부분 코드 작성
🌱 작업한 브랜치
- feature/#116
- CountingView 나타나면 Workout 세션 시작하도록 함
- Workout 종료 버튼 누르면 운동 새션 끝나도록 함
- 종료 버튼 .onDisappear()에 들어 있는 로직이 다른 탭뷰로 스와이핑 할 때마다 실행되는 문제 있어서 NavigationLink의 label 값을 Button뷰로 변경함
- Resolved: #
> Feature/#116 - watchOS 백그라운드 동작 처리

- MC3_Tering/MC3-Tering-Watch-Watch-App-Info.plist
- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
- MC3_Tering/MC3_Tering/View/TestPhoneView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView.swift
🌱 작업한 브랜치
- feature/#119
- 데이터 넘겨주기
- Resolved: #119
> [Feat]#119-스윙 데이터 넘겨주기

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering/Model/CoreData/UserData/UserData+CoreDataProperties.swift
- MC3_Tering/MC3_Tering/Model/CoreData/UserInfo.xcdatamodeld/UserInfo.xcdatamodel/contents
- MC3_Tering/MC3_Tering/Model/CoreData/WorkOutData/WorkOutData+CoreDataClass.swift
- MC3_Tering/MC3_Tering/Model/CoreData/WorkOutData/WorkOutData+CoreDataProperties.swift
- MC3_Tering/MC3_Tering/Model/WorkOutDataModel.swift
- MC3_Tering/MC3_Tering/View/MainView/MainView.swift
- MC3_Tering/MC3_Tering/View/OnboardingView/OnboardingView.swift
🌱 작업한 브랜치
- feature/#121
- Resolved: #121
> Feature/#121 CoreData 속성 변경

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering/Model/ViewModelPhone.swift
- MC3_Tering/MC3_Tering/View/Extension/DateExtension.swift
- MC3_Tering/MC3_Tering/View/MainView/ChartView/MonthChartView.swift
- MC3_Tering/MC3_Tering/View/MainView/ChartView/RecordChartView.swift
- MC3_Tering/MC3_Tering/View/MainView/ChartView/SixMonthsChartView.swift
- MC3_Tering/MC3_Tering/View/MainView/ChartView/WeekChartview.swift
- MC3_Tering/MC3_Tering/View/MainView/ChartView/YearChartView.swift
- MC3_Tering/MC3_Tering/View/MainView/MainView.swift
- MC3_Tering/MC3_Tering/View/Resource/CustomSegmentedView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
- iOS 차트 구현 중
- 
🌱 작업한 브랜치
- feature/#129
- Resolved: #
> Feature/#129 - iOS 차트 구현

- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
- 제곧내
🌱 작업한 브랜치
- feature/#130
- watchOS SelectView.swift의 종료 버튼에도 연습 종료 시 동작 로직 추가
- Resolved: #
> [Fix] #130 - watchOS 스윙 목표 달성 화면에서 결과 안넘어가는 오류 수정

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
🌱 작업한 브랜치
- feature/#133
- disabled(true) 추가해서 화면 터치 시 내비게이션 동작 막음
- Resolved: #
> [Fix] #133 - 스윙 횟수 확인 뷰 터치 시 내비게이션 동작 막아줌

- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
🌱 작업한 브랜치
- feature/#137
- CheckingSwingView 부분을 ReadyView와 같은 형식으로 수정해줌
- Resolved: #137
> [Fix] #137 - watchOS CheckingSwingView 화면 어두운 문제 해결

- MC3_Tering/MC3_Tering.xcodeproj/project.pbxproj
- MC3_Tering/MC3_Tering/Model/WorkOutDataModel.swift
- MC3_Tering/MC3_Tering_Watch Watch App/MC3_Tering_WatchApp.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/EtcView/CompleteView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/ResultView/ResultView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/SelectView.swift
🌱 작업한 브랜치
- feature/#146
- CoreData 부분을 워치에서 사용
- 우선 타겟 설정을 지정하고 실행했을 때 돌아가는거 같기는 합니다.
- Resolved: #146
> [Feat]#146- Core Data 워치에 인식

- MC3_Tering/MC3_Tering_Watch Watch App/MLModel/TennisClassifierViewModel.swift
- MC3_Tering/MC3_Tering_Watch Watch App/View/WorkoutView/CountingView.swift
🌱 작업한 브랜치
- feature/#이슈번호
- TennisClassifierViewModel 코드 리팩토링
- Resolved: #
> TennisClassifierViewModel 코드 리팩토링
